services:
  versalog.server:
    image: ${DOCKER_REGISTRY-}versalogserver
    build:
      context: .
      dockerfile: VersaLog.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"   
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: versalog
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

